# Generated by Django 3.0.3 on 2020-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Account',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('username', models.CharField(max_length=300)),
        #         ('name', models.CharField(max_length=300)),
        #         ('email', models.CharField(max_length=200)),
        #         ('role', models.CharField(max_length=10)),
        #         ('review', models.CharField(max_length=1)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='File',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=300)),
        #         ('file_name', models.CharField(max_length=300)),
        #         ('authors', models.CharField(max_length=200)),
        #         ('publishers', models.CharField(max_length=200)),
        #         ('datePublished', models.DateField(verbose_name='Date Published')),
        #         ('tags', models.CharField(max_length=200)),
        #     ],
        # ),
    ]
